sudo: required
dist: trusty

# travis-ci runs by default on ancient Ubuntu 12.04 (precise), with support until XXX
# following options will give us Ubuntu 14.04 (trusty)
services:
  - docker

language: bash

services:
  - docker

before_install:
  - docker pull grzanka/cmssw_810:pre4
  - curl -J -o sample.root "https://cernbox.cern.ch/index.php/s/WUQIFkrR8auOHDn/download"
  - md5sum sample.root

script:
  - docker run --rm -v `pwd`:/home/cmsbuild/src -it grzanka/cmssw_810:pre4 /bin/sh -c "cp -r src/* CMSSW_8_1_0_pre4/src && chown -R cmsbuild:cmsbuild CMSSW_8_1_0_pre4 && cd CMSSW_8_1_0_pre4/src && bash test.sh"

notifications:
  email:
    - leszek.grzanka@cern.ch
    - jan.kaspar@cern.ch
