sudo: required
dist: trusty


services:
  - docker

language: bash

services:
  - docker

before_install:
  - docker pull grzanka/cmssw_810:pre4
  - curl -J -o sample.srs "https://cernbox.cern.ch/index.php/s/KSxpCPSmZX3TFMS/download"

script:
  - docker run --rm -v `pwd`:/home/cmsbuild/src -it grzanka/cmssw_810:pre4 /bin/sh -c "cp -r src/* CMSSW_8_1_0_pre4/src && chown -R cmsbuild:cmsbuild CMSSW_8_1_0_pre4 && cd CMSSW_8_1_0_pre4/src && bash test.sh"

notifications:
  email:
    - leszek.grzanka@cern.ch
    - jan.kaspar@cern.ch
