sudo: required

services:
  - docker

language: bash

services:
  - docker

before_install:
  - docker pull grzanka/cmssw_810_pre1
  - wget https://cernbox.cern.ch/index.php/s/KSxpCPSmZX3TFMS/download -o sample.srs

script:
  - docker run --rm -v `pwd`:/home/cmsbuild/src -it grzanka/cmssw_810_pre1 /bin/sh -c "cp -r src/* CMSSW_8_1_0_pre1/src && chown -R cmsbuild:cmsbuild CMSSW_8_1_0_pre1 && cd CMSSW_8_1_0_pre1/src && bash test.sh"