sudo: required

services:
  - docker

language: bash

services:
  - docker

before_install:
  - docker pull grzanka/cmssw_810_pre1
  - wget https://cernbox.cern.ch/index.php/s/KSxpCPSmZX3TFMS/download -o sample.srs

script:
  - docker run --rm -v `pwd`:/home/cmsbuild/src -it grzanka/cmssw_810_pre1 /bin/sh -c build.sh
